# https://hub.docker.com/_/postgres
# Use postgres/example user/password credentials
version: '3.8'

services:
  # soj_backend:
  #   container_name: soj_backend
  #   image: nick3141/nickkelly.dev-backend:latest
  #   restart: unless-stopped
  #   ports:
  #     - "${PORT}:${PORT}"
  #   env_file: .env.production
  #   volumes:
  #     - "${LOG_DIR}"
  #   depends_on:
  #     - soj_redis
  #     - soj_pg

  # https://hub.docker.com/_/redis
  soj_redis:
    container_name: soj_redis
    image: redis:6.0.9
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PSW}

  soj_pg:
    container_name: soj_pg
    image: postgres:12.4
    restart: unless-stopped
    ports:
      - "${PG_PORT}:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PSW}
      POSTGRES_DB: ${PG_DB}
