# https://hub.docker.com/_/postgres
# Use postgres/example user/password credentials
version: '3'

services:
  # https://hub.docker.com/_/redis
  nk_redis_dev:
    container_name: nk_redis_dev
    image: redis:6.0.9
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PSW}
    volumes:
      - './_v_redis_data:/data'

  nk_pg_dev:
    container_name: nk_pg_dev
    image: postgres:12.4
    restart: unless-stopped
    ports:
      - "${PG_PORT}:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PSW}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - './_v_pg_data:/var/lib/postgresql/data'
